# -*- coding: gbk -*-

import urllib2
from time import sleep

def getData(city,ChineseName):

    success = False
    flag_url = 0
    while not success:
        if flag_url >= 5:
            return None  #try this url 5 times, if no response, return 
            break
        try:
            url='http://www.pm25.in'+city
            req = urllib2.Request(url)
            response = urllib2.urlopen(req,timeout = 5)   # deal with timeout 
            html = response.read()
            success=True
        except:
            sleep(1)
            flag_url += 1

    #print html

    time = '\xe6\x95\xb0\xe6\x8d\xae\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4\xef\xbc\x9a'#'数据更新时间'
    #time2=time.decode('gbk').encode('utf8')
    indextime = html.find(time)

    temp = html.find(time,indextime+len(time))
    indextime = temp
    
    datetime=html[indextime+len(time):indextime+len(time)+len('2015-09-30 11:00:00')]
    print datetime+' '

    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html,"html.parser")
    
    f = open('/home/ec2-user/pm25_wangluyi/pm25.txt','a')   # directory 
    row=1
    countRow=len(soup.tbody.contents)


    while (row<countRow):
    #try:
        f.write(datetime+" ")
        f.write(ChineseName+" ")
        print ChineseName,city
        column=1
        
        while (column<= 3   ):
            try:
                f.write(soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')+" ")
            except:
                f.write('error'+' ')
            try:
                print soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')
            except:
                print 'error'
            #print soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')
            column=column+2

        while (column== 5   ):
            if(len(soup.tbody.contents[int(row)].contents[int(column)])==0):
                f.write('unknown ')
            else:
                try:
                    f.write(soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')+" ")
                except:
                    f.write('error'+' ')
                #print soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')
            column=column+2

        #多于1种首要污染物, more than 1 first pollutant 
        while (column==7   ):
            if(len(soup.tbody.contents[int(row)].contents[int(column)])>2): #检测3种及以上污染物的标签结构, record tags for 3 more kinds of pollutant 
                f_special = open('/home/ec2-user/pm25_wangluyi/special_number_of_pollutant.txt','a')   
                f_special.write(soup)
                f_special.write('\n')
                f_special.close()
                f.write('lengthMoreThanTwo ')
                
            if(len(soup.tbody.contents[int(row)].contents[int(column)])==2):  #2种首要污染物, 2 critical pollutants 

                if(  str(soup.tbody.contents[int(row)].contents[int(column)]).count('\n')>5  ):
                    f_special = open('/home/ec2-user/pm25_wangluyi/special_number_of_pollutant.txt','a')   
                    f_special.write(soup)
                    f_special.write('\n')
                    f_special.close()

                start=soup.tbody.contents[int(row)].contents[int(column)].contents[0].find('\n',0)
                end=soup.tbody.contents[int(row)].contents[int(column)].contents[0].find('\n',1)
                f.write(soup.tbody.contents[int(row)].contents[int(column)].contents[0][start+1:end].encode('gbk')+",")
            #需要循环??? need loop? 

                start = str(soup.tbody.contents[int(row)].contents[int(column)].contents[1]).find('\n',0)
                start += len('                      ')
                end = str(soup.tbody.contents[int(row)].contents[int(column)].contents[1]).find('\n',start)
                f.write( str(soup.tbody.contents[int(row)].contents[int(column)].contents[1])[start+1:end].decode('utf8').encode('gbk')+" ")

            else:
                f.write(soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')+" ")
            
            column=column+2

        while ( column<=21 ):
            #考虑如果表格中该格子为空的情况, if no data in the table cell 
            try:
                if (len(soup.tbody.contents[int(row)].contents[int(column)].contents[0])==0):
                    f.write('nodata'+' ')
                else:
                    f.write(soup.tbody.contents[int(row)].contents[int(column)].contents[0].encode('gbk')+" ")
            except:
                f.write('error'+' ')
                
            column=column+2

        row=row+2
        f.write("\n")

    f.close()


if __name__=="__main__":

    ChineseCityName =  ["阿坝州",
                        "阿克苏地区",
                        "阿拉善盟",
                        "阿勒泰地区",
                        "阿里地区",
                        "安康",
                        "安庆",
                        "鞍山",
                        "安顺",
                        "安阳",
                        "白城",
                        "百色",
                        "白山",
                        "白银",
                        "蚌埠",
                        "保定",
                        "宝鸡",
                        "保山",
                        "包头",
                        "巴彦淖尔",
                        "巴中",
                        "北海",
                        "北京",
                        "本溪",
                        "毕节",
                        "滨州",
                        "博州",
                        "亳州",
                        "沧州",
                        "长春",
                        "常德",
                        "昌都地区",
                        "昌吉州",
                        "长沙",
                        "常熟",
                        "长治",
                        "常州",
                        "朝阳",
                        "潮州",
                        "承德",
                        "成都",
                        "郴州",
                        "赤峰",
                        "池州",
                        "重庆",
                        "崇左",
                        "楚雄州",
                        "滁州",
                        "大连",
                        "大理州",
                        "丹东",
                        "大庆",
                        "大同",
                        "大兴安岭地",
                        "大兴安岭地区",
                        "达州",
                        "德宏州",
                        "德阳",
                        "德州",
                        "定西",
                        "迪庆州",
                        "东莞",
                        "东营",
                        "鄂尔多斯",
                        "恩施州",
                        "鄂州",
                        "防城港",
                        "佛山",
                        "抚顺",
                        "阜新",
                        "阜阳",
                        "富阳",
                        "福州",
                        "抚州",
                        "甘南州",
                        "赣州",
                        "甘孜州",
                        "广安",
                        "广元",
                        "广州",
                        "贵港",
                        "桂林",
                        "贵阳",
                        "果洛州",
                        "固原",
                        "哈尔滨",
                        "海北州",
                        "海东地区",
                        "海口",
                        "海门",
                        "海南州",
                        "海西州",
                        "哈密地区",
                        "邯郸",
                        "杭州",
                        "汉中",
                        "鹤壁",
                        "河池",
                        "合肥",
                        "鹤岗",
                        "黑河",
                        "衡水",
                        "衡阳",
                        "和田地区",
                        "河源",
                        "菏泽",
                        "贺州",
                        "红河州",
                        "淮安",
                        "淮北",
                        "怀化",
                        "淮南",
                        "黄冈",
                        "黄南州",
                        "黄山",
                        "黄石",
                        "呼和浩特",
                        "惠州",
                        "葫芦岛",
                        "呼伦贝尔",
                        "湖州",
                        "佳木斯",
                        "吉安",
                        "江门",
                        "江阴",
                        "胶南",
                        "胶州",
                        "焦作",
                        "嘉兴",
                        "嘉峪关",
                        "揭阳",
                        "吉林",
                        "即墨",
                        "济南",
                        "金昌",
                        "晋城",
                        "景德镇",
                        "荆门",
                        "荆州",
                        "金华",
                        "济宁",
                        "金坛",
                        "晋中",
                        "锦州",
                        "九江",
                        "酒泉",
                        "鸡西",
                        "句容",
                        "开封",
                        "喀什地区",
                        "克拉玛依",
                        "克州",
                        "库尔勒",
                        "昆明",
                        "昆山",
                        "来宾",
                        "莱芜",
                        "莱西",
                        "莱州",
                        "廊坊",
                        "兰州",
                        "拉萨",
                        "乐山",
                        "凉山州",
                        "连云港",
                        "聊城",
                        "辽阳",
                        "辽源",
                        "丽江",
                        "临安",
                        "临沧",
                        "临汾",
                        "临夏州",
                        "临沂",
                        "林芝地区",
                        "丽水",
                        "六盘水",
                        "柳州",
                        "溧阳",
                        "陇南",
                        "龙岩",
                        "娄底",
                        "六安",
                        "漯河",
                        "洛阳",
                        "泸州",
                        "吕梁",
                        "马鞍山",
                        "茂名",
                        "眉山",
                        "梅州",
                        "绵阳",
                        "牡丹江",
                        "南昌",
                        "南充",
                        "南京",
                        "南宁",
                        "南平",
                        "南通",
                        "南阳",
                        "那曲地区",
                        "内江",
                        "宁波",
                        "宁德",
                        "怒江州",
                        "盘锦",
                        "攀枝花",
                        "蓬莱",
                        "平顶山",
                        "平度",
                        "平凉",
                        "萍乡",
                        "普洱",
                        "莆田",
                        "濮阳",
                        "黔东南州",
                        "黔南州",
                        "黔西南州",
                        "青岛",
                        "庆阳",
                        "清远",
                        "秦皇岛",
                        "钦州",
                        "齐齐哈尔",
                        "七台河",
                        "泉州",
                        "曲靖",
                        "衢州",
                        "日喀则地区",
                        "日照",
                        "荣成",
                        "乳山",
                        "三门峡",
                        "三明",
                        "三亚",
                        "上海",
                        "商洛",
                        "商丘",
                        "上饶",
                        "山南地区",
                        "汕头",
                        "汕尾",
                        "韶关",
                        "绍兴",
                        "邵阳",
                        "沈阳",
                        "深圳",
                        "石河子",
                        "石家庄",
                        "十堰",
                        "石嘴山",
                        "寿光",
                        "双鸭山",
                        "朔州",
                        "四平",
                        "松原",
                        "绥化",
                        "遂宁",
                        "随州",
                        "宿迁",
                        "苏州",
                        "宿州",
                        "塔城地区",
                        "泰安",
                        "太仓",
                        "太原",
                        "台州",
                        "泰州",
                        "唐山",
                        "天津",
                        "天水",
                        "铁岭",
                        "铜川",
                        "通化",
                        "通辽",
                        "铜陵",
                        "铜仁地区",
                        "吐鲁番地区",
                        "瓦房店",
                        "潍坊",
                        "威海",
                        "渭南",
                        "文登",
                        "文山州",
                        "温州",
                        "乌海",
                        "武汉",
                        "芜湖",
                        "吴江",
                        "五家渠",
                        "乌兰察布",
                        "乌鲁木齐",
                        "武威",
                        "无锡",
                        "吴忠",
                        "梧州",
                        "厦门",
                        "西安",
                        "湘潭",
                        "湘西州",
                        "襄阳",
                        "咸宁",
                        "咸阳",
                        "孝感",
                        "锡林郭勒盟",
                        "兴安盟",
                        "邢台",
                        "西宁",
                        "新乡",
                        "信阳",
                        "新余",
                        "忻州",
                        "西双版纳州",
                        "宣城",
                        "许昌",
                        "徐州",
                        "雅安",
                        "延安",
                        "延边州",
                        "盐城",
                        "阳江",
                        "阳泉",
                        "扬州",
                        "烟台",
                        "宜宾",
                        "宜昌",
                        "宜春",
                        "伊春",
                        "伊犁哈萨克",
                        "伊犁哈萨克州",
                        "银川",
                        "营口",
                        "鹰潭",
                        "义乌",
                        "宜兴",
                        "益阳",
                        "永州",
                        "岳阳",
                        "玉林",
                        "榆林",
                        "运城",
                        "云浮",
                        "玉树州",
                        "玉溪",
                        "枣庄",
                        "张家港",
                        "张家界",
                        "张家口",
                        "章丘",
                        "张掖",
                        "漳州",
                        "湛江",
                        "肇庆",
                        "昭通",
                        "招远",
                        "郑州",
                        "镇江",
                        "中山",
                        "中卫",
                        "周口",
                        "舟山",
                        "珠海",
                        "诸暨",
                        "驻马店",
                        "株洲",
                        "淄博",
                        "自贡",
                        "资阳",
                        "遵义"]

    nameCity = ["/abazhou",
                "/akesudiqu",
                "/alashanmeng",
                "/aletaidiqu",
                "/alidiqu",
                "/ankang",
                "/anqing",
                "/anshan",
                "/anshun",
                "/anyang",
                "/baicheng",
                "/baise",
                "/baishan",
                "/baiyin",
                "/bengbu",
                "/baoding",
                "/baoji",
                "/baoshan",
                "/baotou",
                "/bayannaoer",
                "/bazhong",
                "/beihai",
                "/beijing",
                "/benxi",
                "/bijie",
                "/binzhou",
                "/boertala",
                "/bozhou",
                "/cangzhou",
                "/changchun",
                "/changde",
                "/changdudiqu",
                "/changjizhou",
                "/changsha",
                "/changshu",
                "/changzhi",
                "/changzhou",
                "/chaoyang",
                "/chaozhou",
                "/chengde",
                "/chengdu",
                "/chenzhou",
                "/chifeng",
                "/chizhou",
                "/chongqing",
                "/chongzuo",
                "/chuxiongzhou",
                "/chuzhou",
                "/dalian",
                "/dalizhou",
                "/dandong",
                "/daqing",
                "/datong",
                "/daxinganlingde",
                "/daxinganlingdiqu",
                "/dazhou",
                "/dehongzhou",
                "/deyang",
                "/dezhou",
                "/dingxi",
                "/diqingzhou",
                "/dongguan",
                "/dongying",
                "/eerduosi",
                "/enshizhou",
                "/ezhou",
                "/fangchenggang",
                "/foshan",
                "/fushun",
                "/fuxin",
                "/fuyang",
                "/fuyangshi",
                "/fuzhou",
                "/fuzhoushi",
                "/gannanzhou",
                "/ganzhou",
                "/ganzizhou",
                "/guangan",
                "/guangyuan",
                "/guangzhou",
                "/guigang",
                "/guilin",
                "/guiyang",
                "/guoluozhou",
                "/guyuan",
                "/haerbin",
                "/haibeizhou",
                "/haidongdiqu",
                "/haikou",
                "/haimen",
                "/hainanzhou",
                "/haixizhou",
                "/hamidiqu",
                "/handan",
                "/hangzhou",
                "/hanzhong",
                "/hebi",
                "/hechi",
                "/hefei",
                "/hegang",
                "/heihe",
                "/hengshui",
                "/hengyang",
                "/hetiandiqu",
                "/heyuan",
                "/heze",
                "/hezhou",
                "/honghezhou",
                "/huaian",
                "/huaibei",
                "/huaihua",
                "/huainan",
                "/huanggang",
                "/huangnanzhou",
                "/huangshan",
                "/huangshi",
                "/huhehaote",
                "/huizhou",
                "/huludao",
                "/hulunbeier",
                "/huzhou",
                "/jiamusi",
                "/jian",
                "/jiangmen",
                "/jiangyin",
                "/jiaonan",
                "/jiaozhou",
                "/jiaozuo",
                "/jiaxing",
                "/jiayuguan",
                "/jieyang",
                "/jilin",
                "/jimo",
                "/jinan",
                "/jinchang",
                "/jincheng",
                "/jingdezhen",
                "/jingmen",
                "/jingzhou",
                "/jinhua",
                "/jining",
                "/jintan",
                "/jinzhong",
                "/jinzhou",
                "/jiujiang",
                "/jiuquan",
                "/jixi",
                "/jurong",
                "/kaifeng",
                "/kashediqu",
                "/kelamayi",
                "/kezhou",
                "/kuerle",
                "/kunming",
                "/kunshan",
                "/laibin",
                "/laiwu",
                "/laixi",
                "/laizhou",
                "/langfang",
                "/lanzhou",
                "/lasa",
                "/leshan",
                "/liangshanzhou",
                "/lianyungang",
                "/liaocheng",
                "/liaoyang",
                "/liaoyuan",
                "/lijiang",
                "/linan",
                "/lincang",
                "/linfen",
                "/linxiazhou",
                "/linyi",
                "/linzhidiqu",
                "/lishui",
                "/liupanshui",
                "/liuzhou",
                "/liyang",
                "/longnan",
                "/longyan",
                "/loudi",
                "/luan",
                "/luohe",
                "/luoyang",
                "/luzhou",
                "/lvliang",
                "/maanshan",
                "/maoming",
                "/meishan",
                "/meizhou",
                "/mianyang",
                "/mudanjiang",
                "/nanchang",
                "/nanchong",
                "/nanjing",
                "/nanning",
                "/nanping",
                "/nantong",
                "/nanyang",
                "/naqudiqu",
                "/neijiang",
                "/ningbo",
                "/ningde",
                "/nujiangzhou",
                "/panjin",
                "/panzhihua",
                "/penglai",
                "/pingdingshan",
                "/pingdu",
                "/pingliang",
                "/pingxiang",
                "/puer",
                "/putian",
                "/puyang",
                "/qiandongnanzhou",
                "/qiannanzhou",
                "/qianxinanzhou",
                "/qingdao",
                "/qingyang",
                "/qingyuan",
                "/qinhuangdao",
                "/qinzhou",
                "/qiqihaer",
                "/qitaihe",
                "/quanzhou",
                "/qujing",
                "/quzhou",
                "/rikazediqu",
                "/rizhao",
                "/rongcheng",
                "/rushan",
                "/sanmenxia",
                "/sanming",
                "/sanya",
                "/shanghai",
                "/shangluo",
                "/shangqiu",
                "/shangrao",
                "/shannandiqu",
                "/shantou",
                "/shanwei",
                "/shaoguan",
                "/shaoxing",
                "/shaoyang",
                "/shenyang",
                "/shenzhen",
                "/shihezi",
                "/shijiazhuang",
                "/shiyan",
                "/shizuishan",
                "/shouguang",
                "/shuangyashan",
                "/shuozhou",
                "/siping",
                "/songyuan",
                "/suihua",
                "/suining",
                "/suizhou",
                "/suqian",
                "/suzhou",
                "/suzhoushi",
                "/tachengdiqu",
                "/taian",
                "/taicang",
                "/taiyuan",
                "/taizhou",
                "/taizhoushi",
                "/tangshan",
                "/tianjin",
                "/tianshui",
                "/tieling",
                "/tongchuan",
                "/tonghua",
                "/tongliao",
                "/tongling",
                "/tongrendiqu",
                "/tulufandiqu",
                "/wafangdian",
                "/weifang",
                "/weihai",
                "/weinan",
                "/wendeng",
                "/wenshanzhou",
                "/wenzhou",
                "/wuhai",
                "/wuhan",
                "/wuhu",
                "/wujiang",
                "/wujiaqu",
                "/wulanchabu",
                "/wulumuqi",
                "/wuwei",
                "/wuxi",
                "/wuzhong",
                "/wuzhou",
                "/xiamen",
                "/xian",
                "/xiangtan",
                "/xiangxizhou",
                "/xiangyang",
                "/xianning",
                "/xianyang",
                "/xiaogan",
                "/xilinguolemeng",
                "/xinganmeng",
                "/xingtai",
                "/xining",
                "/xinxiang",
                "/xinyang",
                "/xinyu",
                "/xinzhou",
                "/xishuangbannazhou",
                "/xuancheng",
                "/xuchang",
                "/xuzhou",
                "/yaan",
                "/yanan",
                "/yanbianzhou",
                "/yancheng",
                "/yangjiang",
                "/yangquan",
                "/yangzhou",
                "/yantai",
                "/yibin",
                "/yichang",
                "/yichun",
                "/yichunshi",
                "/yilihasake",
                "/yilihasakezhou",
                "/yinchuan",
                "/yingkou",
                "/yingtan",
                "/yiwu",
                "/yixing",
                "/yiyang",
                "/yongzhou",
                "/yueyang",
                "/yulin",
                "/yulinshi",
                "/yuncheng",
                "/yunfu",
                "/yushuzhou",
                "/yuxi",
                "/zaozhuang",
                "/zhangjiagang",
                "/zhangjiajie",
                "/zhangjiakou",
                "/zhangqiu",
                "/zhangye",
                "/zhangzhou",
                "/zhanjiang",
                "/zhaoqing",
                "/zhaotong",
                "/zhaoyuan",
                "/zhengzhou",
                "/zhenjiang",
                "/zhongshan",
                "/zhongwei",
                "/zhoukou",
                "/zhoushan",
                "/zhuhai",
                "/zhuji",
                "/zhumadian",
                "/zhuzhou",
                "/zibo",
                "/zigong",
                "/ziyang",
                "/zunyi"]

    
    for i in range(0,len(ChineseCityName)):
        getData(nameCity[i],ChineseCityName[i])
        
